services:
  postgres:
    image: postgres:16
    container_name: cyberready_db
    restart: always
    environment:
      POSTGRES_DB: cyberready
      POSTGRES_USER: elizaveta
      POSTGRES_PASSWORD: abrikos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elizaveta -d cyberready"]
      interval: 10s
      retries: 5
      timeout: 5s

  grafana:
    image: grafana/grafana:10.4.0
    container_name: cyberready_grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - TZ=Europe/Moscow
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  client:
    build: ./frontend
    ports:
      - "3001:3001"  
    volumes:
      - ./frontend:/app
    depends_on:
      - server

  server:
    build: ./backend
    container_name: cyberready_server
    restart: always
    environment:
      - POSTGRES_DB=cyberready
      - POSTGRES_USER=elizaveta
      - POSTGRES_PASSWORD=abrikos
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./frontend:/app/frontend  # Монтируем фронтенд

volumes:
  postgres_data:
  grafana_data: